SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE users
(
  id         INT UNSIGNED AUTO_INCREMENT COMMENT '識別ID' PRIMARY KEY                   NOT NULL AUTO_INCREMENT COMMENT 'ID',
  created_at DATETIME            DEFAULT CURRENT_TIMESTAMP                             NOT NULL COMMENT '登録日時',
  updated_at DATETIME            DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '更新日時'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='ユーザーテーブル';

CREATE TABLE users_body
(
  id         INT UNSIGNED AUTO_INCREMENT COMMENT '識別ID' PRIMARY KEY,
  user_id    INT UNSIGNED                        NOT NULL,
  sex        CHAR(1) DEFAULT '0' NOT NULL NOT NULL COMMENT '性別',
  height     INT                                 NULL,
  weight     INT                                 NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP  NOT NULL COMMENT '登録日時',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP  NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='ユーザー身体管理テーブル';

SET FOREIGN_KEY_CHECKS = 1;